### ISSUE TITLE
execption triggered in notify(): Error occurred while handling event 'Write Event'

### ISSUE THREAD

**Issue by juntujerry** [ThomasGerstenberg/blatann#139] opened 2023-08-01 13:09 UTC
in event_type.py,
I have trigged this exception
"Error occurred while handling event 'Write Event'. Sender: Characteristic:  , CharProps(w), attributes: [ 
u
t
f
8],  Event Args: WriteEventArgs(value= HEX"

However this notification error does not affect sender system. and it happened sporadically.

why is this happened, does it indicate that I've send anything wrong?

Thanks.

**Comment by ThomasGerstenberg** [comment] 2023-08-08 04:44
Would you be able to provide logs at DEBUG level? looks like it's trying to set the character prop attributes to `utf8` rather than the actual props

**Comment by ThomasGerstenberg** [comment] 2023-11-19 05:50
I think this issue is now fixed. Closing this issue for now, can reopen if it's still reproducible on latest master

**Closed by ThomasGerstenberg** 2023-11-19 05:50 UTC
